In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/cross-sell-cb-432/probs_432_3_2.csv
/kaggle/input/cross-sell-cb-432/probs_432_1_2.csv
/kaggle/input/cross-sell-cb-432/probs_432_1_4.csv
/kaggle/input/cross-sell-cb-432/probs_432_2_2.csv
/kaggle/input/cross-sell-cb-432/probs_432_0_4.csv
/kaggle/input/cross-sell-cb-432/probs_432_3_0.csv
/kaggle/input/cross-sell-cb-432/probs_432_2_4.csv
/kaggle/input/cross-sell-cb-432/probs_432_3_1.csv
/kaggle/input/cross-sell-cb-432/probs_432_0_0.csv
/kaggle/input/cross-sell-cb-432/probs_432_0_2.csv
/kaggle/input/cross-sell-cb-432/model_stats.csv
/kaggle/input/cross-sell-cb-432/probs_432_2_1.csv
/kaggle/input/cross-sell-cb-432/probs_432_4_0.csv
/kaggle/input/cross-sell-cb-432/custom.css
/kaggle/input/cross-sell-cb-432/__notebook__.ipynb
/kaggle/input/cross-sell-cb-432/probs_432_1_0.csv
/kaggle/input/cross-sell-cb-432/probs_432_3_4.csv
/kaggle/input/cross-sell-cb-432/probs_432_2_3.csv
/kaggle/input/cross-sell-cb-432/__results__.html
/kaggle/input/cross-sell-cb-432/__output__.json
/kaggle/inp

# Generate Submission File

In [2]:
def generate_submission_file(probs_df):
    
    submission = pd.read_csv('../input/avcrosssell/sample_submission.csv')

    submission['Response'] = probs_df

    submission.to_csv('submission.csv',index=False)

    print(submission.head())

In [3]:
def get_probs_file_name(fname,model):
    
    if model == 'lgb':
        
        fpath = '../input/cross-sell-lightgbm/' + fname
        
    if model == 'xgb':
        
        fpath = '../input/lets-get-rid-of-the-patients-xgboost/probs/' + fname
        
    if model == 'catboost-32':
        
        fpath = '../input/cross-sell-cb-32/' + fname[10:]
        
    if model == 'catboost-432':
        
        fpath = '../input/cross-sell-cb-432/' + fname[10:]
    
    if model == 'catboost-73':
        
        fpath = '../input/cross-sell-cb-73/' + fname[10:]
        
    if model == 'catboost-1':
        
        fpath = '../input/cross-sell-cb-1/' + fname[10:]
        
    if model == 'catboost-2':
        
        fpath = '../input/cross-sell-cb-2/' + fname[10:]
    
    return fpath

In [4]:
sample_probs_file = pd.read_csv('../input/cross-sell-lightgbm/probs.csv')

sample_probs_file.head()

id  Response
0  381110  0.001325
1  381111  0.295264
2  381112  0.289682
3  381113  0.007488
4  381114  0.001115

In [5]:
model_stats_catboost_32 = pd.read_csv('../input/cross-sell-cb-32/model_stats.csv')

model_stats_catboost_432 = pd.read_csv('../input/cross-sell-cb-432/model_stats.csv')

model_stats_catboost_73 = pd.read_csv('../input/cross-sell-cb-73/model_stats.csv')

model_stats_catboost_1 = pd.read_csv('../input/cross-sell-cb-1/model_stats.csv')

model_stats_catboost_2 = pd.read_csv('../input/cross-sell-cb-2/model_stats.csv')

model_stats_lgb = pd.read_csv('../input/cross-sell-lightgbm/model_stats.csv')

model_stats_xgb = pd.read_csv('../input/cross-sell-xgboost/model_stats.csv')

In [6]:
##ALL
probs_file_cat_32 = pd.read_csv('../input/cross-sell-cb-32/probs.csv')

probs_file_cat_432 = pd.read_csv('../input/cross-sell-cb-432/probs.csv')

probs_file_cat_2 = pd.read_csv('../input/cross-sell-cb-2/probs.csv')

probs_file_cat_1 = pd.read_csv('../input/cross-sell-cb-1/probs.csv')

probs_file_cat_73 = pd.read_csv('../input/cross-sell-cb-73/probs.csv')

probs_file_lgb = pd.read_csv('../input/cross-sell-lightgbm/probs.csv')

probs_file_xgb = pd.read_csv('../input/cross-sell-xgboost/probs.csv')

In [7]:
probs_cb = (probs_file_cat_73.iloc[:,1:]+probs_file_cat_32.iloc[:,1:]+probs_file_cat_432.iloc[:,1:]+probs_file_cat_1.iloc[:,1:]+probs_file_cat_2.iloc[:,1:])/5 
probs_ensemble = 0.5*probs_file_cat_73.iloc[:,1:] + 0.5*probs_file_xgb.iloc[:,1:]
probs_ensemble

Response
0       0.000743
1       0.307575
2       0.289092
3       0.007392
4       0.000443
...          ...
127032  0.000533
127033  0.367856
127034  0.000354
127035  0.000277
127036  0.002135

[127037 rows x 1 columns]

In [8]:
generate_submission_file(probs_ensemble)

       id  Response
0  381110  0.000743
1  381111  0.307575
2  381112  0.289092
3  381113  0.007392
4  381114  0.000443


# Get Min Loss Indices

In [9]:
min_loss_index_lgb = np.argsort(model_stats_lgb.validation_loss.values)

min_loss_index_lgb

array([ 26,  27,  28,  93,  92,  25,  11,  90,  10,  94,  91,  30,  56,
        29,  57,  34,  58,  68,  31,  59,  32,  65,  55, 108,  23,  12,
       107,  33,  24,  87,  22, 106,  52,  88,  69,  86,  13,  51,   9,
         7,   6, 109,  79,  20,  78,   5,   1,  67,  66,   4,  89,  21,
        46,  54,  76, 121,  75,  53,   0, 122,  77,  48, 101,  99, 100,
        95,   3,   2, 105,  98, 115, 104,   8,  74, 103, 120, 118,  14,
        97,  72, 124,  16, 102,  71,  18, 116,  15,  70, 117,  45,  80,
        83,  62,  60,  47,  50,  73, 119, 123,  19,  61,  17,  81,  96,
        49,  64,  84, 110, 114,  82, 112,  85,  63, 111, 113,  36,  38,
        39,  37,  35,  40,  43,  41,  44,  42])

In [10]:
min_loss_index_xgb = np.argsort(model_stats_xgb.validation_loss.values)

min_loss_index_xgb

array([ 28,  27,  25,  26,  29,  10,  14,  12,  32,  34,  33,  13,  90,
        66,  94,  11,  31,  55,  30,  56,  65,  91,  20,  68,  93,  22,
        50,  88,  92,  85,  21,  23,  69,  89,  59,  24,  51,  87,  57,
        53,  58,  67,  54,  52,  86,  79,  75,   9, 107,   8, 106, 105,
        77,   7,   6, 108, 109,   5,  76,  78, 115,   0,  97, 119, 117,
        95,   2,   3, 118, 121, 122,   1,  96, 116,  99,   4, 124,  98,
        47, 104, 123,  45,  49, 101, 100, 120,  48, 103,  71,  73,  72,
        46,  70,  74, 102,  19,  62,  15,  17,  18,  63,  16,  61,  60,
        83,  64,  80,  84, 111,  81, 110, 114,  82, 112, 113,  35,  36,
        38,  37,  39,  42,  43,  40,  44,  41])

In [11]:
min_loss_index_cat_32 = np.argsort(model_stats_catboost_32.validation_loss.values)

min_loss_index_cat_32

array([13, 11, 12, 10, 14, 24, 22, 23, 21, 20,  0,  3,  9,  2,  1,  8,  4,
        5,  7,  6, 16, 19, 15, 17, 18])

In [12]:
min_loss_index_cat_432 = np.argsort(model_stats_catboost_432.validation_loss.values)

min_loss_index_cat_432

array([ 0,  2,  4,  3,  1,  6,  9,  5,  7,  8, 23, 24, 21, 20, 22, 11, 13,
       10, 14, 12, 18, 17, 16, 19, 15])

In [13]:
min_loss_index_cat_73 = np.argsort(model_stats_catboost_73.validation_loss.values)

min_loss_index_cat_73

array([ 4,  2,  3,  0,  1, 17,  9,  6,  5,  8, 16,  7, 15, 18, 19, 20, 23,
       22, 24, 21, 10, 12, 14, 13, 11])

In [14]:
min_loss_index_cat_1 = np.argsort(model_stats_catboost_1.validation_loss.values)

min_loss_index_cat_1

array([ 7,  8,  9,  5,  6, 10, 11, 12, 13, 14, 23, 21, 22, 20, 24, 15, 18,
       19, 16, 17,  3,  0,  1,  2,  4])

In [15]:
min_loss_index_cat_2 = np.argsort(model_stats_catboost_2.validation_loss.values)

min_loss_index_cat_2

array([ 9,  5,  8,  6,  7,  0,  3,  4,  2, 20,  1, 24, 23, 21, 16, 22, 15,
       19, 17, 18, 13, 11, 14, 12, 10])

# Get Max AUC indices

In [16]:
max_auc_index_catboost_32 = np.argsort(-model_stats_catboost_32.oof_roc.values)

max_auc_index_catboost_32

array([11, 13, 14,  9, 12, 10,  8,  5,  6,  7, 22, 24, 23, 21, 20,  0,  3,
        1,  2,  4, 16, 19, 18, 15, 17])

In [17]:
max_auc_index_catboost_432 = np.argsort(-model_stats_catboost_432.oof_roc.values)

max_auc_index_catboost_432

array([ 0,  4,  2,  3,  1,  6,  9,  8,  5,  7, 23, 24, 21, 20, 22, 10, 13,
       11, 14, 12, 18, 16, 17, 19, 15])

In [18]:
max_auc_index_catboost_73 = np.argsort(-model_stats_catboost_73.oof_roc.values)

max_auc_index_catboost_73

array([ 9, 17,  6,  5,  4,  8, 16,  7,  1, 15,  3, 18,  0,  2, 19, 23, 24,
       20, 21, 22, 10, 12, 14, 13, 11])

In [19]:
max_auc_index_catboost_1 = np.argsort(-model_stats_catboost_1.oof_roc.values)

max_auc_index_catboost_1

array([ 7,  9,  8,  5,  6, 21, 10, 11, 20, 23, 22, 12, 24, 13, 14, 15, 18,
       19, 17, 16,  3,  0,  1,  2,  4])

In [20]:
max_auc_index_catboost_2 = np.argsort(-model_stats_catboost_2.oof_roc.values)

max_auc_index_catboost_2

array([20,  5, 24, 21,  9, 23,  8,  6, 22,  7, 17, 15, 16, 18, 19,  0,  3,
        2,  4,  1, 13, 11, 12, 14, 10])

In [21]:
max_auc_index_lgb = np.argsort(-model_stats_lgb.oof_roc.values)

max_auc_index_lgb

array([ 26,  27,  28,  29,  68,  25,  93,  65,  69,  30,  66,  67,  12,
        11,   7,  14,  92,  13,  34,  94,   8,  90,  31,  33,  10,   5,
        32,   9,   6,  91,  57,  56,  53,  58,  50,  52,  55,  54, 121,
       120,  51,  59, 122, 124,  72, 123,  74, 106, 107,  70, 108,  71,
        98,  87,  23, 105,  73,  89, 109,  95,  24,  86,  20,  21,  88,
        99,  97,  22,  85,  96,   3,   4, 115,  46,   1, 119, 117,   2,
         0,  18, 118, 116,  63,  48,  15,  45,  62,  60,  61,  47,  49,
        16,  64,  17, 101,  19,  83, 104, 102, 103, 100,  82,  84,  80,
        81,  78,  75,  77,  76,  79, 113, 111, 112, 114, 110,  37,  36,
        38,  35,  39,  43,  40,  42,  41,  44])

In [22]:
max_accuracy_index_xgb = np.argsort(-model_stats_xgb.oof_roc.values)

max_accuracy_index_xgb

array([ 25,  28,  29,  26,  27,   9,  66,  34,  32,  65,  14,   5,   8,
        33,   7,  67,  31,   6,  68,  69,  30,  12,  10,  94,  90,  59,
        13,  55,  58, 121,  91,  92,  11,  56,  57, 122,  93,  50,  71,
       120,  73,  70,  72,  51, 124,  54,  53, 123,  74,  88, 107,  89,
         0,  52,  95, 105,  87,  85, 108,  97,  96, 106,   2,   3,   1,
       115,  99,  21, 109,  86,  20,   4,  98,  24,  22,  23, 119, 117,
        62, 116,  63, 118,  47,  61,  60,  49,  16,  45,  64,  17,  19,
        15,  48,  18,  79,  46,  84,  80,  83, 104,  75, 101,  82, 103,
       100, 102, 110,  81,  77, 111, 114,  78, 112,  76, 113,  35,  38,
        37,  36,  39,  42,  40,  43,  44,  41])

# Ensembling based on Min Loss

In [23]:
probs_df_loss = pd.read_csv('../input/cross-sell-lightgbm/probs.csv')

In [24]:
def cal_probs_loss(model_name,model_stats_df,min_loss_idx_arr,model_iter):
    
    probs_cal_loss = np.zeros(shape=(127037,1))

    for i,idx in enumerate(min_loss_idx_arr):
    
        probs_cal_loss += pd.read_csv(get_probs_file_name(model_stats_df.iloc[idx,0],model_name)).iloc[:,1:]
    
        if i == model_iter-1:
        
            break
        
    probs_df_loss.iloc[:,1:] = probs_cal_loss

    #print(probs_df_loss.head())

    return probs_cal_loss/model_iter
    

# Ensembling based on Max Accuracy

In [25]:
probs_df_acc = pd.read_csv('../input/cross-sell-lightgbm/probs.csv')

In [26]:
def cal_probs_acc(model_name,model_stats_df,max_accuracy_idx_arr,model_iter):
    
    probs_cal_acc = np.zeros(shape=(127037,))

    for i,idx in enumerate(max_accuracy_idx_arr):

        probs_cal_acc += pd.read_csv(get_probs_file_name(model_stats_df.iloc[idx,0],model_name)).iloc[:,1:]

        if i ==model_iter-1:

            break

    #print(probs_cal_acc.head())
    
    return probs_cal_acc/model_iter
    